-- SHOW DATABASES;
-- USE Agent_Info;
-- SHOW TABLES;
-- SELECT *FROM AGENTS;

-- TODO:Substring 
-- SELECT SUBSTRING(email,1,5) AS TRUNCATED FROM AGENTS;
-- SELECT CONCAT(SUBSTRING(email,1,5),"..." )AS TRUNCATED FROM AGENTS;




